services:
  kube:
    image: bitnami/kubectl
    volumes:
      - ${KUBECONFIG}:/kube/config.yaml
    environment:
      - KUBECONFIG=/kube/config.yaml
    command: "port-forward pod/${PODNAME:-'mongo-0'} --address 0.0.0.0 ${PORT:-'27017'}"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=kube
    ports:
      - 8081:8081
    restart: unless-stopped
