from python:3.9

RUN pip install selenium
RUN pip install web3
RUN pip install SQLAlchemy
RUN pip install psycopg2
RUN pip install web3 requests
RUN pip install pandas
RUN pip install twisted
RUN pip install flask
RUN pip install matplotlib
RUN pip install webdriver_manager
RUN pip install pycryptodome
RUN pip install ecdsa
RUN pip install pysha3
RUN pip install ipfs-api
